### PR TITLE
cast msg to str

### PR DESCRIPTION
**Pull request by Sail338**
- cast msg to str so we can log other than strings and dont have to do casting ourselves, alternatively can check the type and throw an exception

### CODE REVIEW

**Comment by rangat** [comment]
There, we fixed it for you...

**Comment by 11** [comment]
This will fix it, but I'm going to take this and push the `str()` function call into `_log`, rather than implementing it in the different log levels

**Comment by 11** [comment]
thanks for finding this!!!!!

**Comment by 11** [comment]
changes have been made, on `master` -- some other files needed to be reworked with this update :+1:.

**Pull request closed without merging**
